#!/usr/bin/env python3
"""
One-time migration tool: walk the old 4D5A.github.io Jekyll source and
generate matching redirect-stub files in this repo, so every URL that used
to resolve on 4d5a.github.io keeps resolving (as a meta-refresh + canonical
redirect to the same path on failclosed.com).

Usage:
    python scripts/generate_redirect_stubs.py <path-to-4D5A.github.io-source>

Safe to re-run: it overwrites previously generated stubs.
"""
import re
import sys
from pathlib import Path

FRONT_MATTER_RE = re.compile(r"^---\s*\n(.*?\n)---\s*(\n|\Z)", re.DOTALL)
PERMALINK_RE = re.compile(r"^permalink:\s*(\S+)\s*$", re.MULTILINE)

STUB_HEADER = "This file is generated by scripts/generate_redirect_stubs.py — do not hand-edit."


def read_front_matter(path: Path) -> str | None:
    text = path.read_text(encoding="utf-8")
    m = FRONT_MATTER_RE.match(text)
    return m.group(1) if m else None


def extract_permalink(front_matter: str) -> str | None:
    m = PERMALINK_RE.search(front_matter)
    return m.group(1) if m else None


def write_stub(dest_path: Path, permalink: str | None, note: str) -> None:
    dest_path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["---", f"layout: redirect", f"# {note}"]
    if permalink:
        lines.insert(2, f"permalink: {permalink}")
    lines.append("---")
    dest_path.write_text("\n".join(lines) + "\n", encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(1)

    src_root = Path(sys.argv[1]).resolve()
    dest_root = Path(__file__).resolve().parent.parent  # repo root (4d5a.github.io/)

    generated = []

    # --- 1. Posts: same filename in _posts/, same global permalink pattern
    #     (/:year-:month-:day-:title/) on both sites reproduces the same URL.
    src_posts = src_root / "_posts"
    dest_posts = dest_root / "_posts"
    for post_file in sorted(src_posts.rglob("*.md")):
        stub_path = dest_posts / post_file.name
        write_stub(stub_path, None, f"redirect stub for {post_file.relative_to(src_root).as_posix()}")
        generated.append(stub_path.relative_to(dest_root).as_posix())

    # --- 2. Pages with an explicit `permalink:` in front matter (including
    #     404.html and the homepage).
    candidates = list((src_root / "pages").rglob("*.md")) + [src_root / "404.html"]
    for page_file in sorted(candidates):
        fm = read_front_matter(page_file)
        if not fm:
            continue
        permalink = extract_permalink(fm)
        rel = page_file.relative_to(src_root)
        if permalink:
            stub_path = dest_root / "pages" / rel.relative_to("pages") if rel.parts[0] == "pages" else dest_root / rel
            write_stub(stub_path, permalink, f"redirect stub for {rel.as_posix()} (permalink: {permalink})")
            generated.append(stub_path.relative_to(dest_root).as_posix())
        else:
            # No explicit permalink -> Jekyll uses the default path-based URL.
            # Reproduce that by mirroring the file's own relative path.
            stub_path = dest_root / rel
            write_stub(stub_path, None, f"redirect stub for {rel.as_posix()} (default path-based URL)")
            generated.append(stub_path.relative_to(dest_root).as_posix())

    # --- 3. Root-level files with default (path-based) permalinks.
    for name in ["categories.html", "tags.html", "aitags.html"]:
        src_file = src_root / name
        if src_file.exists():
            stub_path = dest_root / name
            write_stub(stub_path, None, f"redirect stub for {name} (default path-based URL)")
            generated.append(stub_path.relative_to(dest_root).as_posix())

    # feed.xml / podcast.xml: best-effort browser redirect. Real feed readers
    # don't execute meta-refresh/JS, so these two also need a true 301 via
    # the Cloudflare CSV (see ../cloudflare-redirects.csv).
    for name in ["feed.xml", "podcast.xml"]:
        src_file = src_root / name
        if src_file.exists():
            stub_path = dest_root / name
            write_stub(stub_path, f"/{name}", f"redirect stub for {name} (best-effort; feed readers need the Cloudflare 301)")
            generated.append(stub_path.relative_to(dest_root).as_posix())

    print(f"Generated {len(generated)} redirect stubs:")
    for g in generated:
        print(f"  {g}")


if __name__ == "__main__":
    main()
