name: Redirect Site CI
on: [push, pull_request]
permissions:
  contents: read
  pages: write
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true
      - name: Setup Pages
        id: configure-pages
        uses: actions/configure-pages@v5
      - name: Setup CI config
        run: |
          echo "---" > _config_ci.yml
          echo "baseurl: ${{ steps.configure-pages.outputs.base_path }}" >> _config_ci.yml
      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --future --config _config_ci.yml,_config.yml
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
